CREATE TABLE IF NOT EXISTS system_admins (email TEXT PRIMARY KEY COLLATE NOCASE, name TEXT NOT NULL, google_sub TEXT UNIQUE, created_at TEXT NOT NULL, confirmed_at TEXT);
CREATE TABLE IF NOT EXISTS auth_identities (email TEXT PRIMARY KEY COLLATE NOCASE, google_sub TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS auth_sessions (token_hash TEXT PRIMARY KEY, email TEXT NOT NULL, google_sub TEXT NOT NULL, portal_role TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS auth_sessions_email ON auth_sessions(email);
CREATE TABLE IF NOT EXISTS auth_challenges (nonce TEXT PRIMARY KEY, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS auth_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS protect_last_system_admin BEFORE DELETE ON system_admins
WHEN OLD.google_sub IS NOT NULL AND (SELECT COUNT(*) FROM system_admins WHERE google_sub IS NOT NULL)<=1
BEGIN SELECT RAISE(ABORT, 'LAST_SYSTEM_ADMIN'); END;
CREATE TRIGGER IF NOT EXISTS protect_last_pending_admin BEFORE DELETE ON system_admins
WHEN (SELECT COUNT(*) FROM system_admins)<=1
BEGIN SELECT RAISE(ABORT, 'LAST_SYSTEM_ADMIN'); END;
